In [1]:
from pyspark.sql import SparkSession as SS, functions as F
from pyspark.sql.window import Window

spark = SS.builder.appName("DatasetGermanCreditRisk").getOrCreate()
windowSpec = Window.partitionBy("Housing").orderBy("Credit amount")

df = spark.read.csv("german_credit_data.csv", header=True, inferSchema=True)
df.show()

# Menampilkan data jenis kelamin, umur, dan pekerjaan
df.select("Sex","Age","Job").show()

# Menampilkan data yang memiliki umur di atas 35
df.filter(df["Age"] > 35).show()

# Menjumlahkan total kredit berdasarkan jenis kelamin
df.groupBy("Sex").sum("Credit amount").show()

# Menambahkan kolom Born yang berisi tahun kelahiran
df.withColumn("Born", 2025 - df["Age"]).show()

# Mengurutkan data berdasarkan kategori Housing dan mengurutkannya lagi berdasarkan Credit amount
df.withColumn(("Rank"), F.rank().over(windowSpec)).show()

25/09/05 20:39:59 WARN Utils: Your hostname, UbuntuVM resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
25/09/05 20:39:59 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/09/05 20:40:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
25/09/05 20:40:11 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
 Schema: _c0, Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
Expected: _c0 but found:
CSV file: file:///home/vboxuser/praktikumBigData/german_credit_data.csv

+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+
|_c0|Age|   Sex|Job|Housing|Saving accounts|Checking account|Credit amount|Duration|            Purpose|
+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+
|  0| 67|  male|  2|    own|             NA|          little|         1169|       6|           radio/TV|
|  1| 22|female|  2|    own|         little|        moderate|         5951|      48|           radio/TV|
|  2| 49|  male|  1|    own|         little|              NA|         2096|      12|          education|
|  3| 45|  male|  2|   free|         little|          little|         7882|      42|furniture/equipment|
|  4| 53|  male|  2|   free|         little|          little|         4870|      24|                car|
|  5| 35|  male|  1|   free|             NA|              NA|         9055|      36|          education|
|  6| 53|  male|  2|    own|     quite rich|              NA|         2835|      24|furniture/equipment|
|  7| 35|  male|  3|   rent|         little|        moderate|         6948|      36|                car|
|  8| 61|  male|  1|    own|           rich|              NA|         3059|      12|           radio/TV|
|  9| 28|  male|  3|    own|         little|        moderate|         5234|      30|                car|
| 10| 25|female|  2|   rent|         little|        moderate|         1295|      12|                car|
| 11| 24|female|  2|   rent|         little|          little|         4308|      48|           business|
| 12| 22|female|  2|    own|         little|        moderate|         1567|      12|           radio/TV|
| 13| 60|  male|  1|    own|         little|          little|         1199|      24|                car|
| 14| 28|female|  2|   rent|         little|          little|         1403|      15|                car|
| 15| 32|female|  1|    own|       moderate|          little|         1282|      24|           radio/TV|
| 16| 53|  male|  2|    own|             NA|              NA|         2424|      24|           radio/TV|
| 17| 25|  male|  2|    own|             NA|          little|         8072|      30|           business|
| 18| 44|female|  3|   free|         little|        moderate|        12579|      24|                car|
| 19| 31|  male|  2|    own|     quite rich|              NA|         3430|      24|           radio/TV|
+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+
only showing top 20 rows

+------+---+---+
|   Sex|Age|Job|
+------+---+---+
|  male| 67|  2|
|female| 22|  2|
|  male| 49|  1|
|  male| 45|  2|
|  male| 53|  2|
|  male| 35|  1|
|  male| 53|  2|
|  male| 35|  3|
|  male| 61|  1|
|  male| 28|  3|
|female| 25|  2|
|female| 24|  2|
|female| 22|  2|
|  male| 60|  1|
|female| 28|  2|
|female| 32|  1|
|  male| 53|  2|
|  male| 25|  2|
|female| 44|  3|
|  male| 31|  2|
+------+---+---+
only showing top 20 rows

25/09/05 20:40:12 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
 Schema: _c0, Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
Expected: _c0 but found:
CSV file: file:///home/vboxuser/praktikumBigData/german_credit_data.csv

+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+
|_c0|Age|   Sex|Job|Housing|Saving accounts|Checking account|Credit amount|Duration|            Purpose|
+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+
|  0| 67|  male|  2|    own|             NA|          little|         1169|       6|           radio/TV|
|  2| 49|  male|  1|    own|         little|              NA|         2096|      12|          education|
|  3| 45|  male|  2|   free|         little|          little|         7882|      42|furniture/equipment|
|  4| 53|  male|  2|   free|         little|          little|         4870|      24|                car|
|  6| 53|  male|  2|    own|     quite rich|              NA|         2835|      24|furniture/equipment|
|  8| 61|  male|  1|    own|           rich|              NA|         3059|      12|           radio/TV|
| 13| 60|  male|  1|    own|         little|          little|         1199|      24|                car|
| 16| 53|  male|  2|    own|             NA|              NA|         2424|      24|           radio/TV|
| 18| 44|female|  3|   free|         little|        moderate|        12579|      24|                car|
| 20| 48|  male|  2|    own|         little|              NA|         2134|       9|                car|
| 21| 44|  male|  2|   rent|     quite rich|          little|         2647|       6|           radio/TV|
| 22| 48|  male|  1|   rent|         little|          little|         2241|      10|                car|
| 23| 44|  male|  2|    own|       moderate|        moderate|         1804|      12|                car|
| 25| 36|  male|  1|    own|         little|          little|         1374|       6|furniture/equipment|
| 26| 39|  male|  1|    own|         little|              NA|          426|       6|           radio/TV|
| 27| 42|female|  2|   rent|           rich|            rich|          409|      12|           radio/TV|
| 29| 63|  male|  2|    own|         little|          little|         6836|      60|           business|
| 30| 36|  male|  2|    own|           rich|        moderate|         1913|      18|           business|
| 33| 57|  male|  1|   rent|             NA|              NA|         1264|      12|           business|
| 37| 37|  male|  2|    own|         little|            rich|         2100|      18|           radio/TV|
+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+
only showing top 20 rows

+------+------------------+
|   Sex|sum(Credit amount)|
+------+------------------+
|female|            892110|
|  male|           2379148|
+------+------------------+

25/09/05 20:40:13 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
 Schema: _c0, Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
Expected: _c0 but found:
CSV file: file:///home/vboxuser/praktikumBigData/german_credit_data.csv

+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+----+
|_c0|Age|   Sex|Job|Housing|Saving accounts|Checking account|Credit amount|Duration|            Purpose|Born|
+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+----+
|  0| 67|  male|  2|    own|             NA|          little|         1169|       6|           radio/TV|1958|
|  1| 22|female|  2|    own|         little|        moderate|         5951|      48|           radio/TV|2003|
|  2| 49|  male|  1|    own|         little|              NA|         2096|      12|          education|1976|
|  3| 45|  male|  2|   free|         little|          little|         7882|      42|furniture/equipment|1980|
|  4| 53|  male|  2|   free|         little|          little|         4870|      24|                car|1972|
|  5| 35|  male|  1|   free|             NA|              NA|         9055|      36|          education|1990|
|  6| 53|  male|  2|    own|     quite rich|              NA|         2835|      24|furniture/equipment|1972|
|  7| 35|  male|  3|   rent|         little|        moderate|         6948|      36|                car|1990|
|  8| 61|  male|  1|    own|           rich|              NA|         3059|      12|           radio/TV|1964|
|  9| 28|  male|  3|    own|         little|        moderate|         5234|      30|                car|1997|
| 10| 25|female|  2|   rent|         little|        moderate|         1295|      12|                car|2000|
| 11| 24|female|  2|   rent|         little|          little|         4308|      48|           business|2001|
| 12| 22|female|  2|    own|         little|        moderate|         1567|      12|           radio/TV|2003|
| 13| 60|  male|  1|    own|         little|          little|         1199|      24|                car|1965|
| 14| 28|female|  2|   rent|         little|          little|         1403|      15|                car|1997|
| 15| 32|female|  1|    own|       moderate|          little|         1282|      24|           radio/TV|1993|
| 16| 53|  male|  2|    own|             NA|              NA|         2424|      24|           radio/TV|1972|
| 17| 25|  male|  2|    own|             NA|          little|         8072|      30|           business|2000|
| 18| 44|female|  3|   free|         little|        moderate|        12579|      24|                car|1981|
| 19| 31|  male|  2|    own|     quite rich|              NA|         3430|      24|           radio/TV|1994|
+---+---+------+---+-------+---------------+----------------+-------------+--------+-------------------+----+
only showing top 20 rows

25/09/05 20:40:14 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
 Schema: _c0, Age, Sex, Job, Housing, Saving accounts, Checking account, Credit amount, Duration, Purpose
Expected: _c0 but found:
CSV file: file:///home/vboxuser/praktikumBigData/german_credit_data.csv

+---+---+------+---+-------+---------------+----------------+-------------+--------+---------------+----+
|_c0|Age|   Sex|Job|Housing|Saving accounts|Checking account|Credit amount|Duration|        Purpose|Rank|
+---+---+------+---+-------+---------------+----------------+-------------+--------+---------------+----+
|519| 36|  male|  2|   free|             NA|              NA|          700|       6|       radio/TV|   1|
|354| 46|  male|  2|   free|     quite rich|              NA|          727|      10|      education|   2|
|123| 63|  male|  2|   free|         little|            rich|          781|      10|            car|   3|
|377| 36|  male|  2|   free|             NA|              NA|          846|       7|       radio/TV|   4|
|648| 38|  male|  2|   free|         little|            rich|          947|      24|            car|   5|
|349| 32|  male|  2|   free|           rich|        moderate|         1136|       9|      education|   6|
| 72| 51|  male|  3|   free|         little|          little|         1164|       8|vacation/others|   7|
|187| 68|  male|  0|   free|         little|        moderate|         1175|      16|            car|   8|
|429| 55|female|  0|   free|         little|          little|         1190|      18|        repairs|   9|
|711| 35|female|  2|   free|         little|          little|         1198|       6|      education|  10|
|360| 61|  male|  2|   free|             NA|        moderate|         1239|      18|      education|  11|
|611| 48|female|  1|   free|       moderate|            rich|         1240|      10|            car|  12|
|757| 39|  male|  2|   free|             NA|            rich|         1271|      15|       radio/TV|  13|
|609| 45|  male|  2|   free|             NA|              NA|         1300|      15|            car|  14|
|545| 43|  male|  2|   free|         little|          little|         1333|      24|            car|  15|
|150| 42|  male|  2|   free|       moderate|              NA|         1346|       6|       radio/TV|  16|
|702| 47|female|  2|   free|       moderate|            rich|         1377|      24|       radio/TV|  17|
|878| 27|  male|  3|   free|         little|          little|         1422|       9|            car|  18|
|853| 32|  male|  1|   free|         little|          little|         1442|      18|            car|  19|
|852| 35|  male|  2|   free|         little|              NA|         1471|      15|       radio/TV|  20|
+---+---+------+---+-------+---------------+----------------+-------------+--------+---------------+----+
only showing top 20 rows